# REGRESSION

In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv(r"C:\Users\ambad\Downloads\car_age_price.csv")
data.head()

Year   Price
0  2018  465000
1  2019  755000
2  2019  700000
3  2018  465000
4  2018  465000

In [3]:
y=data['Price']
x=data['Year']

In [4]:
y.shape

(112,)

In [5]:
y=np.array(y)
y

array([465000, 755000, 700000, 465000, 465000, 350000, 425000, 575000,
       509999, 575000, 500000, 500000, 500000, 600000, 475000, 500000,
       500000, 550000, 500000, 500000, 500000, 500000, 434999, 550000,
       550000, 550000, 550000, 550000, 550000, 550000, 650000, 550000,
       550000, 550000, 450000, 550000, 550000, 486000, 475000, 545000,
       525000, 600000, 550000, 550000, 550000, 450000, 500000, 450000,
       396000, 600000, 325000, 550000, 345000, 345000, 525000, 550000,
       341000, 550000, 450000, 550000, 490000, 540000, 540000, 595000,
       490000, 495000, 525000, 400000, 465000, 300000, 450000, 490000,
       300000, 320000, 490000, 490000, 450000, 325000, 409999, 400000,
       390000, 390000, 390000, 480000, 325000, 320000, 520000, 520000,
       520000, 520000, 520000, 520000, 520000, 520000, 520000, 520000,
       520000, 640000, 700000, 600000, 350000, 400000, 350000, 375000,
       400000, 400000, 300000, 375000, 300000, 425000, 420000, 425000],
     

In [6]:
y=np.array(y)
y=y.reshape(-1,1)
y.shape

(112, 1)

In [7]:
x.shape

(112,)

In [8]:
x=np.array(x)
x=x.reshape(-1,1)
x.shape

(112, 1)

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
sc=StandardScaler()
x=sc.fit_transform(x)
y=sc.fit_transform(y)

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=.20)

In [12]:
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(89, 1) (23, 1) (89, 1) (23, 1)


In [13]:
from sklearn.linear_model import LinearRegression
ln_model=LinearRegression()
ln_model.fit(X_train,y_train)
y_prediction=ln_model.predict(X_test)

In [14]:
y_prediction

array([[ 1.28742151],
       [ 0.23888223],
       [ 0.76315187],
       [ 0.76315187],
       [ 0.76315187],
       [-0.80965705],
       [ 0.23888223],
       [ 0.76315187],
       [ 1.28742151],
       [ 1.28742151],
       [-1.85819633],
       [ 0.23888223],
       [-0.80965705],
       [ 1.81169115],
       [ 0.76315187],
       [ 1.28742151],
       [-1.85819633],
       [-0.80965705],
       [ 0.23888223],
       [ 0.23888223],
       [ 0.23888223],
       [ 0.23888223],
       [ 0.23888223]])

In [15]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [16]:
print('mean_squared_error is',mean_squared_error(y_prediction,y_test))
print('mean_absolute_error is',mean_absolute_error(y_prediction,y_test))
print('r2_score is',r2_score(y_prediction,y_test))

mean_squared_error is 0.5247067733340601
mean_absolute_error is 0.5895295935049284
r2_score is 0.4052626156691991


# PREDICTING THE PRICE IN 2022

In [17]:
year_2022=np.array([[2022]])

In [18]:
predicted_price_2022=ln_model.predict(year_2022)
print(f"Predicted price for 2022 Hyundai Grand i10: {predicted_price_2022[0]}")

Predicted price for 2022 Hyundai Grand i10: [1719.84803972]


# LASSO REGRESSION

In [19]:
y=data['Price']
x=data['Year']

In [20]:
x=np.array(x)
x=x.reshape(-1,1)
x.shape

(112, 1)

In [21]:
y=np.array(y)
y=y.reshape(-1,1)
y.shape

(112, 1)

In [22]:
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=.20)

# Train Linear Regression model

In [24]:
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)

LinearRegression()

In [25]:
linear_preds = linear_model.predict(X_test)
linear_preds

array([[600775.91252081],
       [505558.77690466],
       [553167.34471273],
       [553167.34471273],
       [553167.34471273],
       [410341.6412885 ],
       [505558.77690466],
       [553167.34471273],
       [600775.91252081],
       [600775.91252081],
       [315124.50567235],
       [505558.77690466],
       [410341.6412885 ],
       [648384.48032889],
       [553167.34471273],
       [600775.91252081],
       [315124.50567235],
       [410341.6412885 ],
       [505558.77690466],
       [505558.77690466],
       [505558.77690466],
       [505558.77690466],
       [505558.77690466]])

In [26]:
print('mean_squared_error is',mean_squared_error(y_prediction,y_test))
print('mean_absolute_error is',mean_absolute_error(y_prediction,y_test))
print('r2_score is',r2_score(y_prediction,y_test))

mean_squared_error is 237868087695.31924
mean_absolute_error is 480651.88944214705
r2_score is -269615433763.59518


# Train Lasso Regression model

In [27]:
lasso_model = Lasso(alpha=0.1)
lasso_model.fit(X_train, y_train)

Lasso(alpha=0.1)

In [28]:
lasso_preds = lasso_model.predict(X_test)
lasso_preds

array([600775.81201603, 505558.75884159, 553167.28542881, 553167.28542881,
       553167.28542881, 410341.70566715, 505558.75884159, 553167.28542881,
       600775.81201603, 600775.81201603, 315124.65249272, 505558.75884159,
       410341.70566715, 648384.33860324, 553167.28542881, 600775.81201603,
       315124.65249272, 410341.70566715, 505558.75884159, 505558.75884159,
       505558.75884159, 505558.75884159, 505558.75884159])

In [29]:
print('mean_squared_error is',mean_squared_error(y_prediction,y_test))
print('mean_absolute_error is',mean_absolute_error(y_prediction,y_test))
print('r2_score is',r2_score(y_prediction,y_test))

mean_squared_error is 237868087695.31924
mean_absolute_error is 480651.88944214705
r2_score is -269615433763.59518
